services:
  db:
    image: postgres:16
    container_name: pirimatch-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pirimatch
    ports:
      - "5432:5432"
    volumes:
      - pirimatch_pgdata:/var/lib/postgresql/data

volumes:
  pirimatch_pgdata:
